In [37]:
from n71.n71 import jadge_stopword
from nltk import stem
import re
import sys
import collections
from see import see
import numpy as np

In [38]:

p = open('rt-polarity.pos')
pattern = re.compile('[a-zA-Z0-9]')
result_feature = []
with open('n73-feature.txt', 'w') as feature:
    ps = stem.PorterStemmer()
    for st in sentiment:
        wl = st.split()
        label = wl.pop(0)
        for w in wl:
            check = [re.match(pattern, c) for c in w]
            if None not in check and jadge_stopword(ps.stem(w)) == False:
                result_feature.append(ps.stem(w))
    result_ps = list(set(result_feature))
    for rp in result_ps:
        feature.write(rp+'\n')

In [39]:
result = []
sentiment = open(fname)
for st in sentiment:
    wl = st.split()
    label = wl.pop(0)
    if label == '-1':
        result.append(0)
    else:
        result.append(1)
ynpy = np.array(result)
np.save('n73-y.npy', ynpy)
ynpy2 = np.load('n73-y.npy')
print(ynpy2, len(ynpy2))

[0 0 0 ... 0 0 1] 10661


In [40]:
print(len(result_feature), len(set(result_feature)))
feature = {v:k for k, v in enumerate(list(set(result_feature)))}

53245 8289


In [41]:
result_x = []
ps = stem.PorterStemmer()
sentiment = open(fname).readlines()
for st in sentiment:
    wl = st.split()
    label = wl.pop(0)
    x = [0 for i in range(len(feature))]
    for w in wl:
        check = [re.match(pattern, c) for c in w]
        w = ps.stem(w)
        if None not in check and jadge_stopword(w) == False:
            if feature.get(w) is not None:
                x[feature.get(w)] = 1
    result_x += x

In [42]:
xnpy = np.array(result_x)
xnpy = xnpy.reshape(len(ynpy), len(feature))

In [43]:
print(xnpy)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [44]:
np.save('n73-x.npy', xnpy)